### ISSUE TITLE
Shears not working/missing compost items & blocks

### ISSUE THREAD

**Issue by lamoyrl90** [Voronoiii/BYG#21]
MC 1.15.2
BYG 0.2.0

**Comment by AOCAWOL** [comment]
Thank you for reporting we'll be investigating this :)

**Comment by lamoyrl90** [comment]
Also, while I'm shearing these woods, the red spruce leaves don't compost.

Neither do any of the colored spruce saplings that I've tried.

**Comment by AOCAWOL** [comment]
Okay, we'll look into that too, I've updated the name of the Issue :)

**Comment by AOCAWOL** [comment]
Okay I've added the missing compost items/block and fixed shears not working on a few leaves
(They weren't added properly to the Leaves Tag)
I'll be releasing a patch update tomorrow which will contain these fixes :)
