### ISSUE TITLE
Multiple Common set-up crashes

### ISSUE THREAD

**Issue by Excaliburning** [Voronoiii/BYG#22]
Hello,

I've been running in multiple crashes with BYG these days.
Only crash log I've kept for now is [this one](https://gist.github.com/Excaliburning/57e67daeb003f0382c9a42e8658f4d58).

I've ran into common set-up crashes both on client and server load.
They randomly happen, not 100% of the time. I saw in the command something talking about BYGBurnable [in my server's console](https://gist.github.com/Excaliburning/2cfc2248f75decfeb452580814a995df). I'm using [Better Burning](https://www.curseforge.com/minecraft/mc-mods/better-burning) in case it is related for some reason.

Please send a safe-boat ! Removed BYG in the mean time to check if I run into other issues despite this.

**Comment by AOCAWOL** [comment]
What version of the mod is this happening on? If it is for 1.12.2 I, unfortunately, cannot fix those kinds of issues as 1.12.2 builds are made with Mcreator. However, if this is for 1.15.2 builds we can further investigate this.

**Comment by Excaliburning** [comment]
Sorry, forgot to mention this critical "detail".
It's on 1.15.2, latest build as of now (0.2.0).

**Comment by AOCAWOL** [comment]
Awesome thankyou! Could you possibly send your crash report file so we can take a more in-depth look at it?

**Comment by Excaliburning** [comment]
[crash-2020-04-08_22.49.11-server.txt](https://github.com/Voronoiii/BYG/files/4452962/crash-2020-04-08_22.49.11-server.txt)

console debug is now in .gz format, I can't upload it here and have no idea how to open it. If the above can't help you and you need the console file, I'll try to see what I can do about it.

**Comment by AOCAWOL** [comment]
I noticed that the crash report shows you're using other mods, do you know if this issue persists without these other mods present?

**Comment by Artellia** [comment]
I believe I am running into the same issue. For me it is the combination of Biomes You'll Go plus Biomes O'Plenty. BYG on its own seems to start up fine. I'm on 1.15.2, Forge is current as of today, no other mods loaded.
[Biomes_You_Go_0.2.0+BiomesOPlenty-1.15.2-10.0.0.345-universal.txt](https://github.com/Voronoiii/BYG/files/4454348/Biomes_You_Go_0.2.0%2BBiomesOPlenty-1.15.2-10.0.0.345-universal.txt)

**Comment by AOCAWOL** [comment]
Thannkyou, as we believe we have found the root of this issue we will be figuring out a fix and hopefully can get that released as soon as possible :D

**Comment by Voronoiii** [comment]
May be a possible HashSet error as BOP & any other biome mod writes into the fireblock hash by creating a new hashset which in turn can lead to an error. We'll investigate further.

**Comment by Artellia** [comment]
I found a strange solution. I can start without the error reliable if I add a completely unrelated library, "Bookshelf". I am an earlier version of it for support for another mod because their latest two versions also cause a crash on their own. The file I added to my mod folder that seems to have resolved the error is this one: [](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/2898277)

**Comment by Excaliburning** [comment]
I'm using Bookshelf 5.1.10 (issue is not solved with Bookshelf, however this is an alpha release), Biomes O'Plenty and TerraForged.
I believed I wasn't using TerraForged in this case, only Biomes O'Plenty and BYG. This takes out TerraForged for now.

**Comment by Voronoiii** [comment]
And you guys said BYG alone works by itself without problems correct?

**Comment by Artellia** [comment]
yes, it just has a conflict with one of the mods it is listed as compatible with.

**Comment by AOCAWOL** [comment]
We have released a patch update to hopefully resolve this issue, please let us know if the issue persists with this new update:
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/2925445

**Comment by Voronoiii** [comment]
Released a patch:
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/2925445

Comment on this issue if the issue persists. Thanks guys!

**Comment by Artellia** [comment]
> ...please let us know if the issue persists with this new update:

Huzzah! She starts without error on her own, alongside mentioned compatible mods (Traverse, BOP, and TerraForged), and alongside my entire mod list.

**Comment by AOCAWOL** [comment]
Awesome glad it's working!
