### ISSUE TITLE
Podzol Dacite sounds and breaks like dirt

### ISSUE THREAD

**Issue by lamoyrl90** [Voronoiii/BYG#23]
Seems to break easier with a shovel, and sounds like dirt, but it drops dacite cobble.

Dunno if this was intentional, but the overgrown dacite is pickaxe and rock.

Addendum: It would be nice if it was tagged as cobblestone, for crafting purposes.

MC 1.15.2
BYG 0.2.0

**Comment by Voronoiii** [comment]
Fixed this and will be available in the next patch later today. I'll comment once it's released thanks!
