### ISSUE TITLE
No Better Foliage extra leaves on BYG Leaves

### ISSUE THREAD

**Issue by MrProton657** [Voronoiii/BYG#31]
What do I have do type in here to get BYG Leaves added to Better Foliage
![Снимок7](https://user-images.githubusercontent.com/38361990/81403830-87269100-9134-11ea-922c-152a2317a673.PNG)

**Comment by Voronoiii** [comment]
What version?

**Comment by MrProton657** [comment]
BYG 1.7.1
Better Foliage 2.3.1
I know that you dont support MC1.12.2 anymore, because it was written on MCcreator , but I cant find it out by myself, so I would be thankful if you help me if its possiable

**Comment by AOCAWOL** [comment]
So, I know that this is kind of a bummer to hear and I am really sorry but I cannot fix this issue. You see how in that Block Type list you have there. BYG 1.12.2 doesn't have that. Mcreator doesn't work like that. All blocks are separate and their own things. A. Leaves aren't actual leaf blocks and pull from the leaf block properties in vanilla in 1.12.2 BYG, and B. you would essentially have to enter every single block individually, I currently have no idea where in the files the blocks are stored. Mcreator doesn't really show me that kind of information hence why I stopped using it. I know that this is very unfortunate but at this moment there is nothing Voronoii nor I can do to solve this
