### ISSUE TITLE
Problem of 1.7.2 for 1.12 about the dislocation of saplings

### ISSUE THREAD

**Issue by rtxyd** [Voronoiii/BYG#33]
Just like the title says. When I use bone powder on a sapling, the tree spawn away from where I plant it. It causes problem with decorating my home.

**Comment by Voronoiii** [comment]
This happens because of the use of a program called MCreator in 1.12. We can't do anything about this without rewriting the mod and that most likely won't occur as we do not support 1.12. I am closing this as this version is unsupported. Sorry :/

**Comment by rtxyd** [comment]
sad sad，I can't find a better biomes mod than this mod in 1.12 again. 😥
